### PR TITLE
Fix provision w/ Resolver expectations

### LINKED ISSUE #90: Provisio and BF dependency collector combo does not work
BF collector is the new collector present in Maven 3.9.x, can be invoked as:
```
-Daether.dependencyCollector.impl=bf
```

Reason: provisio relies on fact (that is nowhere documented) that Artifact instance sent for collection will be same instance returned. This is nowhere stated nor documented (but 1.9.x resolver w/o BF collector did worked like it, this was undocumented feature).

This IF is wrong, as with BF there are no more `ProvisoArtifact` instances returned, and data loss occurs, for example "unpack" actions are lost:
https://github.com/jvanzyl/provisio/blob/b5a21b0f1fc8500c871c5e2e716a0a02b6c66b13/provisio-core/src/main/java/ca/vanzyl/provisio/MavenProvisioner.java#L454-L463

This expectation is wrong: as if ProvisioArtifact (w/ unpack action) would use range for example, even old collector would have to "explode" the Artifact instances anyway.

### PR DESCRIPTION
**Pull request by cstamas**
Provisio expects same Artifact instance back from resolving it pushed as parameter, but BF collection violates this. There  as an if/else for this case, but else branch had an information loss, where resolver provisio artifact w/ actions like unpack would lost unpack step.

Another fix was that ProvisioArtifact violated immutability, and was handled on many places as mutable (like MavenArtifact).

This expection breaks for example provisio when BF collector is used, that is the default in Maven4, but can be activated in Maven 3.9.x as well (`-Daether.dependencyCollector.impl=bf`).

Fixes #90

### CODE REVIEW

File: provisio-model/src/main/java/ca/vanzyl/provisio/model/ProvisioArtifact.java [hunk 1]
```diff
@@ -146,7 +146,7 @@ public File getFile() {
     }
 
     @Override
-    public Artifact setFile(File file) {
+    public ProvisioArtifact setFile(File file) {
         delegate = delegate.setFile(file);
         return this;
```
Comment (gnodet) [inline provisio-model/src/main/java/ca/vanzyl/provisio/model/ProvisioArtifact.java:151]: Doesn't that break the assumption of the resolver that the Artifact is immutable ?

**Comment by cstamas** [comment]
@wendigo ping

File: provisio-model/src/main/java/ca/vanzyl/provisio/model/ProvisioArtifact.java (hunk 1 above)
Comment (cstamas) [reply provisio-model/src/main/java/ca/vanzyl/provisio/model/ProvisioArtifact.java:151]: Yes, it does, will fix ProvisioArtifact as well

Comment (cstamas) [reply provisio-model/src/main/java/ca/vanzyl/provisio/model/ProvisioArtifact.java]: Fixed

**Comment by wendigo** [comment]
It breaks Trino:

```
ERROR] Failed to execute goal ca.vanzyl.provisio.maven.plugins:provisio-maven-plugin:1.0.24:provision (default-provision) on project trino-exchange-filesystem: Error provisioning assembly.: Duplicate key io.netty:netty-tcnative-boringssl-static (attempted merging values io.netty:netty-tcnative-boringssl-static:jar:2.0.65.Final and io.netty:netty-tcnative-boringssl-static:jar:linux-x86_64:2.0.65.Final) -> [Help 1]
```

File: provisio-core/src/main/java/ca/vanzyl/provisio/MavenProvisioner.java [hunk 2]
```diff
@@ -449,16 +450,25 @@ else if (getArtifactType(artifact.getExtension()) == null) {
             throw new ProvisioningException(e.getMessage(), e);
         }
 
-        Map<String, ProvisioArtifact> artifactMapKeyedByGa = new HashMap<String, ProvisioArtifact>();
+        Map<String, ProvisioArtifact> artifactMapKeyedByGa =
+                new HashMap<>(artifacts.stream().collect(toMap(a -> a.getGroupId() + ":" + a.getArtifactId(), a -> a)));
```
Comment (wendigo) [inline provisio-core/src/main/java/ca/vanzyl/provisio/MavenProvisioner.java:454]: this collect is problematic.

```
.collect(toMap(a -> a.getGroupId() + ":" + a.getArtifactId() + ":" + a.getClassifier(), a -> a)));
```

works for Trino

**Review by wendigo — APPROVED** [review]
